apiVersion: v1
kind: Secret
metadata:
  name: vulnado-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: vulnado
type: Opaque
stringData:
  postgres-password: vulnado
